# -*- coding: utf-8 -*-
# $Rev: 822 $
# $Ver: 0.1.8g1 $
# $Date: 2018-03-20 00:33:18 +0900 (火, 20  3月 2018) $
# $Author: $

# router, server information
node:

    vmx11:
        device: vmx11
        snmp-polling: yes
        follow-remote-log: yes
        mib: 
        tag:


# web application information
webapp:   


# L1 switch information
optic:
    connection:

# tester information
tester:

interface-list:
    - et-0/0/0
    - et-0/0/1


# other default information
default:
    terminal:
        width: 80
        height: 32
    result_folder: result

