default:
    robot-server: 127.0.0.1
    robot-password: password
    renat-master-folder: $RENAT_PATH/config
    calient-master-path: 
    ntm-master-path: 
    ix-remote-tmp: C:/Windows/Temp
    max-retry-for-connect: 3
    interval-between-retry: 15s
    terminal-timeout: 20m
    cmd-auto-check: False
    newline: "\n"
    slack-cmd:  $RENAT_PATH/tools/renat_bot.sh
    slack-proxy: 127.0.0.1
    log-level: ERROR
    ignore-dead-node: FALSE
    mks-console:
        width:  1024
        height: 768
    display:
        width:  1921
        height: 1080

vchannel:
    read-timeout:   180s
    wait-time-before-close: 3m
    read-interval:  0.3s
    ignore-init-finish: False

extra-lib:
    - Tester
    - Hypervisor 
#    - OpticalSwitch
#    - Samurai
#    - Arbor


